# #60: collects raw git facts about the source tree into a generated header.
# Runs at BUILD time (target litepdf_build_id), not configure time: CMake only
# re-configures when VERSION changes, so a configure-time SHA would go stale.
#
# It collects and never classifies -- src/core/Version.cpp decides release vs
# dev. Every git failure records "no answer" and the build continues; the
# classifier treats "no answer" as dev.
#
# Inputs (-D): GIT_EXECUTABLE (may be empty or *-NOTFOUND), SRC, OUT, VERSION.
cmake_minimum_required(VERSION 3.25)

foreach(_var SRC OUT VERSION)
    if(NOT DEFINED ${_var} OR "${${_var}}" STREQUAL "")
        message(FATAL_ERROR "CollectBuildFacts: -D${_var}= is required")
    endif()
endforeach()

# Runs git in SRC; sets out_var to trimmed stdout, or "" on any failure.
function(_litepdf_git out_var)
    set(${out_var} "" PARENT_SCOPE)
    if("${GIT_EXECUTABLE}" STREQUAL "" OR NOT EXISTS "${GIT_EXECUTABLE}")
        return()
    endif()
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" ${ARGN}
        RESULT_VARIABLE _rc
        OUTPUT_VARIABLE _out
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(_rc EQUAL 0)
        set(${out_var} "${_out}" PARENT_SCOPE)
    endif()
endfunction()

# Whole-value sanitize: anything outside [A-Za-z0-9._-] blanks the value, so a
# generated C++ string literal can never be broken by a tag name.
function(_litepdf_sanitize var)
    if(NOT "${${var}}" MATCHES "^[A-Za-z0-9._-]+$")
        set(${var} "" PARENT_SCOPE)
    endif()
endfunction()

set(_toplevel_match 0)
set(_exact_tag "")
set(_describe "")
set(_short_sha "")
set(_dirty 0)

# Only trust git when its top-level IS this source tree. release.yml extracts
# the source tarball inside the checkout, where git would answer for the parent
# repository. REALPATH + lower-case absorbs 8.3 names, junctions and
# drive-letter case.
_litepdf_git(_toplevel rev-parse --show-toplevel)
if(NOT _toplevel STREQUAL "")
    # get_filename_component, not file(REAL_PATH): VS BuildTools' CMake
    # 3.31.6-msvc6 crashes on file(REAL_PATH) for a CJK path (0xC0000409).
    get_filename_component(_top_real "${_toplevel}" REALPATH)
    get_filename_component(_src_real "${SRC}" REALPATH)
    string(TOLOWER "${_top_real}" _top_real)
    string(TOLOWER "${_src_real}" _src_real)
    if(_top_real STREQUAL _src_real)
        set(_toplevel_match 1)
    endif()
endif()

if(_toplevel_match)
    # Only release-shaped tags count: a local tag such as `wip` must never
    # make a release.
    _litepdf_git(_exact_tag describe --tags --exact-match --match "v[0-9]*")
    _litepdf_git(_describe describe --tags --long --dirty --match "v[0-9]*")
    _litepdf_git(_short_sha rev-parse --short HEAD)
    # Same dirty mechanism as _describe, and it works with no tags. It honours
    # .gitmodules `ignore = dirty`, so the MuPDF prune edits do not count.
    # Only tracked files count; untracked files never make a tree dirty.
    # No answer counts as dirty: this is the one fact whose unknown value must
    # be the dev value (a corrupt index can fail this probe while the tag
    # lookup still succeeds).
    # ":dirty" cannot occur in a ref name, so a tag such as v1.3.0-dirty can
    # never be mistaken for the dirty marker.
    _litepdf_git(_always describe --always --dirty=:dirty)
    if(_always STREQUAL "" OR _always MATCHES ":dirty$")
        set(_dirty 1)
    endif()
endif()

_litepdf_sanitize(_exact_tag)
_litepdf_sanitize(_describe)
_litepdf_sanitize(_short_sha)

set(_content "// Generated by cmake/CollectBuildFacts.cmake on every build. Do not edit.
#pragma once
#define LITEPDF_VERSION_TRIPLE \"${VERSION}\"
#define LITEPDF_FACT_TOPLEVEL_MATCH ${_toplevel_match}
#define LITEPDF_FACT_EXACT_TAG \"${_exact_tag}\"
#define LITEPDF_FACT_DESCRIBE \"${_describe}\"
#define LITEPDF_FACT_SHORT_SHA \"${_short_sha}\"
#define LITEPDF_FACT_DIRTY ${_dirty}
")

# Write to a temp file and copy only if different: an unchanged commit keeps
# the header's mtime, so nothing recompiles.
cmake_path(GET OUT PARENT_PATH _out_dir)
file(MAKE_DIRECTORY "${_out_dir}")
file(WRITE "${OUT}.tmp" "${_content}")
file(COPY_FILE "${OUT}.tmp" "${OUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUT}.tmp")
